lib/ticketing_system_web/router.ex
defmodule TicketingSystemWeb.Router do
  use TicketingSystemWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :require_not_authenticated do
    plug TicketingSystem.Plugs.RequireNotAuthenticated, repo: TicketingSystem.Repo
  end

  pipeline :require_authenticated do
    plug TicketingSystem.Plugs.RequireAuthenticated, repo: TicketingSystem.Repo
  end

  pipeline :require_permissions do
    plug TicketingSystem.Plugs.RequirePermissions, repo: TicketingSystem.Repo
  end

  scope "/", TicketingSystemWeb do
    pipe_through [:browser, :require_authenticated]
    resources "/", PageController, only: [:index]
    resources "/session", SessionController, only: [:delete]
  end

  scope "/", TicketingSystemWeb do
    pipe_through [:browser, :require_not_authenticated]

    resources "/registration", RegistrationController, only: [:new, :create]
    resources "/session", SessionController, only: [:new, :create]
  end

  scope "/admin", TicketingSystemWeb do
      pipe_through [:browser, :require_authenticated, :require_permissions]

      resources "/users", UserController, only: [:index, :update]
  end

  scope "/ticket", TicketingSystemWeb do
      pipe_through [:browser, :require_authenticated, :require_permissions]

      resources "/", TicketController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TicketingSystemWeb do
  #   pipe_through :api
  # end
end

lib/ticketing_system_web/views/layout_view.ex
defmodule TicketingSystemWeb.LayoutView do
  use TicketingSystemWeb, :view

  alias TicketingSystem.Accounts

  def logged_in?(conn) do
    Accounts.logged_in?(conn)
  end

  def get_authenticated_user_id(conn) do
     Accounts.get_authenticated_user_id(conn)
  end
end

lib/ticketing_system_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Marce">

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <nav class="navbar navbar-fixed-top navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Ticketing System</a>
      </div>
      <ul class="nav navbar-nav">
        <%= if !logged_in?(@conn) do %>
          <li><%= link "Login", to: session_path(@conn, :new) %></li>
          <li>  <%= link "Register", to: registration_path(@conn, :new) %></li>
        <% end %>
        <%= if logged_in?(@conn) do %>
          <li>  <%= link "Logout", to: session_path(@conn, :delete, get_authenticated_user_id(@conn)), method: :delete  %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <body>
    <div class="container my-custom-container">
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>